'use strict'

const ResponseCode = {
	error : 'ERROR',
	success : 'SUCCESS'
}

const RequestOperation = {
	signinuser : 'SIGNIN_USER',
	signupuser : 'SIGNUP_USER',
	validateuser : 'VALIDATE_USER',
	changepassworduser : 'CHANGE_PASSWORD_USER',
	recoverpassword : 'USER_RECOVER_PASSWORD',
	registerclub : 'REGISTER_CLUB',
	getstatistics : 'GET_STATISTICS',
	sendstatistics : 'SEND_STATISTICS',
	initializepositionclub : 'INITIALIZE_POSITION_CLUB',
	getposition : 'GET_POSITION',
	getpositionclub : 'GET_POSITION_CLUB',
	getpositiontraining : 'GET_POSITION_TRAINING',
	updatepositionclub : 'UPDATE_POSITION_CLUB',
	getincharge : 'GET_INCHARGE',
	getinchargebyemail : 'GET_INCHARGE_BY_EMAIL',
	getinchargeflseat : 'GET_INCHARGE_FL_SEAT',
	getinchargeassigned : 'GET_INCHARGE_ASSIGNED',
	registerincharge: 'REGISTER_INCHARGE',
	updateincharge : 'UPDATE_INCHARGE',
	deleteincharge : 'DELETE_INCHARGE',
	getseat : 'GET_SEAT',
	getseatmanager : 'GET_SEAT_MANAGER',
	getseatcoach : 'GET_SEAT_COACH',
	registerseat : 'REGISTER_SEAT',
	updateseat : 'UPDATE_SEAT',
	deleteseat : 'DELETE_SEAT',
	registerseatincharge : 'REGISTER_SEAT_INCHARGE',
	deleteseatincharge : 'DELETE_SEAT_INCHARGE',
	getteambysede : 'GET_TEAM_BY_SEDE',
	updatepaymentteam : 'UPDATE_PAYMENT_TEAM',
	registerteam : 'REGISTER_TEAM',
	getteam : 'GET_TEAM',
	updateteam : 'UPDATE_TEAM',
	deleteteam : 'DELETE_TEAM',
	deleteteamcoach : 'DELETE_TEAM_COACH',
	registerteamcoach : 'REGISTER_TEAM_COACH',
	getteambyclub : 'GET_TEAM_BY_CLUB',
	getteambymanager : 'GET_TEAM_BY_MANAGER',
	getteambycoach : 'GET_TEAM_BY_COACH',
	getcoach : 'GET_COACH',
	registercoach : 'REGISTER_COACH',
	updatecoach : 'UPDATE_COACH',
	deletecoach: 'DELETE_COACH',
	getcoachbyemail : 'GET_COACH_BY_EMAIL',
	getcoachteam : 'GET_COACH_TEAM',
	getcoachteamseat : 'GET_COACH_TEAM_SEAT',
	getcoachnoteamSeat : 'GET_COACH_NO_TEAM_SEAT',
	getteamseatcoach : 'GET_TEAM_SEAT_COACH',
	getplayer : 'GET_PLAYER',
	updateplayer : 'UPDATE_PLAYER',
	updateplayerheadline : 'UPDATE_PLAYER_HEADLINE',
	getplayerbyemail : 'GET_PLAYER_BY_EMAIL',
	getplayeraction : 'GET_PLAYER_ACTION',
	getplayermatch : 'GET_PLAYER_MATCH',
	getplayerheadline : 'GET_PLAYER_HEADLINE',
	updateparticipationplayers : 'UPDATE_PARTICIPATION_PLAYERS',
	getplayerteam : 'GET_PLAYER_TEAM',
	getmatchplayer : 'GET_MATCH_PLAYER',
	registerplayer : 'REGISTER_PLAYER',
	updateactionplayer : 'UPDATE_ACTION_PLAYER',
	deleteplayer : 'DELETE_PLAYER',
	getmatchcoach : 'GET_MATCH_COACH',
	getmatchteam : 'GET_MATCH_TEAM',
	getmatchescoach : 'GET_MATCHES_COACH',
	getpreviewresult : 'GET_PREVIEW_RESULT',
	updateresultmatch : 'UPDATE_RESULT_MATCH',
	getaction : 'GET_ACTION',
	getactiongroup : 'GET_ACTION_GROUP',
	registermatch : 'REGISTER_MATCH',
	gettraining : 'GET_TRAINING',
	getreportstatistics : 'GET_REPORT_STATISTICS',
	loginadmin: 'LOGIN_ADMIN',
	getapps: 'GET_APPS',
	getappcode: 'GET_APP_CODE',
	getplans: 'GET_PLANS',
	getcustomer: 'GET_CUSTOMER',
	associatecard: 'USER_ASSOCIATE_CARD',
	getplanuser: 'GET_PLAN_USER',
	updateplanuser: 'USER_UPDATE_PLAN',
	validatesubscription: 'USER_VALIDATE_SUBSCRIPTION'
}

module.exports = {
	ResponseCode,
	RequestOperation
}